
  version: '3.8'

  services:
   db:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

   rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # Rabbitmq instance
      - "15672:15672" # Web interface
    networks:
      - app_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

   user_service:
    build:
      context: .
      dockerfile: ServiceFinder/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "5002"
      DatabaseOptions__ConnectionString: Host=db;Port=5432;Database=ServiceFinder;UserId=postgres;Password=root;Pooling=true;
      RabbitMQ__HostName: rabbit
      RabbitMQ__UserName: user
      RabbitMQ__Password: password
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net
    ports:
      - "5002:5002"

   order_service:
    build:
      context: .
      dockerfile: ServiceFinder.OrderService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "5001"
      DatabaseOptions__ConnectionString: Host=db;Port=5432;Database=ServiceFinderOrderService;UserId=postgres;Password=root;Pooling=true;
      RabbitMQ__HostName: rabbit
      RabbitMQ__UserName: user
      RabbitMQ__Password: password
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net
    ports:
      - "5001:5001"
   notification_service:
    build:
      context: .
      dockerfile: ServiceFinder.NotificationsService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "5003"
      RabbitMQ__HostName: rabbit
      RabbitMQ__UserName: user
      RabbitMQ__Password: password
     
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net
    ports:
      - "5003:5003"
  networks:
   app_net:
    driver: bridge

  volumes:
   db_data:
   rabbitmq_data: