name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./ServiceFinder/ServiceFinder.sln

      - name: Build
        run: dotnet build ./ServiceFinder/ServiceFinder.sln --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./ServiceFinder/ServiceFinder.sln

      - name: Build
        run: dotnet build ./ServiceFinder/ServiceFinder.sln --configuration Debug

      - name: Run unit tests
        run: dotnet test ./ServiceFinder/ServiceFinder.UnitTest/ServiceFinder.UnitTest.csproj --no-build --verbosity normal


  analyze:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_BRANCH="${{ github.head_ref }}"
            BASE_BRANCH="${{ github.base_ref }}"
            dotnet-sonarscanner begin /k:"vladzhorov_ServiceFinder" /o:"excitedflow" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.pullrequest.key="$PR_NUMBER" /d:sonar.pullrequest.branch="$PR_BRANCH" /d:sonar.pullrequest.base="$BASE_BRANCH" /d:sonar.coverage.exclusions="ServiceFinder.API/Program.cs"
          else
            dotnet-sonarscanner begin /k:"vladzhorov_ServiceFinder" /o:"excitedflow" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverage.exclusions="ServiceFinder.API/Program.cs"
          fi
          dotnet restore ./ServiceFinder/ServiceFinder.sln
          dotnet build ./ServiceFinder/ServiceFinder.sln --no-restore --configuration Release
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
